version: 2.1

executors:
  java17:
    docker:
      - image: 'cimg/openjdk:17.0'

orbs:
  maven: circleci/maven@1.4.1
  docker: circleci/docker@2.2.0

commands:
  destroy-environment:
    description: Destroy back-end cloudformation stacks given a workflow ID.
    parameters:
      workflowId:
        type: string
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            echo "Destroying udaroute EKS cluster stack: udaroute-eks-cluster"
            #aws cloudformation delete-stack --stack-name udaroute-eks-cluster

jobs:
  build-frontend:
    docker:
      - image: cimg/node:18.16.1
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm --version
            npm install
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  scan-frontend:
    docker:
      - image: cimg/node:18.16.1
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Scan front-end
          command: |
            cd frontend
            npm install
            npm audit --audit-level=critical

  lint-frontend:
    docker:
      - image: cimg/node:18.16.1
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Test front-end
          command: |
            cd frontend
            npm install
            npm run lint

  setup-backend:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]      
      - run: 
          name: Create updated application.properties file
          command: |
            echo "Updating application.properties file in backend/application.properties"
            cd backend
            echo amazon.dynamodb.endpoint=$amazon_dynamodb_endpoint > application.properties
            echo amazon.aws.accesskey=$amazon_aws_accesskey >> application.properties
            echo amazon.aws.secretkey=$amazon_aws_secretkey >> application.properties
            cat application.properties
      - save_cache:
          paths: 
            - backend/application.properties
          key: backend-build

  build-backend:
    executor: java17
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - restore_cache:
           keys: [backend-build]      
      - run:
          name: Compile and Test
          command: |
            cd backend
            mkdir docker
            cat application.properties
            mvn clean test install
            ls -l business/docker
      - run:
          name: Build docker image
          command: |
            cd backend
            docker build --tag=udaroute .
      - run:
          name: Upload docker image to ECR
          command: |
            cd backend
            ls -l business/docker
            echo $ecr_password | docker login --username AWS --password-stdin $ecr_home
            ecrpath=$ecr_home/udaroute:latest
            echo "ERC ID and Image: $ecrpath"
            docker tag udaroute:latest $ecrpath
            docker push $ecrpath

  lint-backend:
    executor: java17
    steps:
      - checkout
      - restore_cache:
           keys: [backend-build]      
      - run:
          name: Checkstyle
          command: |
            cd backend
            mvn compile checkstyle:checkstyle

  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Setup Kubernetes Cluster
          no_output_timeout: 20m
          command: |
            aws cloudformation deploy \
              --template-file aws/cloudformation/eks-cluster-and-nodes.yaml \
              --tags project=udaroute \
              --capabilities CAPABILITY_NAMED_IAM \
              --stack-name udaroute-eks-cluster
      # Destroy environment on failure
      - destroy-environment:
          workflowId: ${CIRCLE_WORKFLOW_ID:0:7}

  deploy-backend:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Deploy backend to EKS cluster
          command: |
            aws eks update-kubeconfig --region us-east-1 --name udaroute
            kubectl create deployment udaroute-deployment --image=$ecr_home/udaroute:latest
            kubectl apply -f aws/udaroute-deployment.yaml
            kubectl expose deployment udaroute-deployment --type=LoadBalancer --name=udaroute-service
            export LOAD_BALANCER_IP="$(kubectl get services udaroute-service -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')"
            export VUE_APP_ROUTE_SERVER_URI=http://${LOAD_BALANCER_IP}:8081
            echo "Exposed URL: $VUE_APP_ROUTE_SERVER_URI"
            echo $VUE_APP_ROUTE_SERVER_URI > backend/server.uri
      - save_cache:
          paths: 
            - backend/server.uri
          key: backend-build            

  deploy-frontend:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build, frontend-build]   
      - run:
          name: Deploy frontend to S3 bucket
          command: |
            cat backend/server.uri
            echo Deploy to S3...
    


workflows:
  default:
    jobs:
      - setup-backend
      - build-backend:
          requires: [setup-backend]
      - lint-backend:
          requires: [build-backend]
      - build-frontend
      - lint-frontend:
          requires: [build-frontend]
      - scan-frontend:
          requires: [build-frontend]
      - deploy-infrastructure
      - deploy-backend:
          requires: [build-backend, deploy-infrastructure]
      - deploy-frontend:
          requires: [build-frontend, deploy-backend]

