version: 2.1

executors:
  java17:
    docker:
      - image: 'cimg/openjdk:17.0'

orbs:
  maven: circleci/maven@1.4.1
  docker: circleci/docker@2.2.0

commands:
  destroy-environment:
    description: Destroy back-end cloudformation stacks given a workflow ID.
    parameters:
      workflowId:
        type: string
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            echo "Destroying udaroute EKS cluster nodes: udaroute-eks-nodes"
            #aws cloudformation delete-stack --stack-name udaroute-eks-nodes
            echo "Destroying udaroute EKS cluster stack: udaroute-eks-cluster"
            #aws cloudformation delete-stack --stack-name udaroute-eks-cluster

jobs:
  build-frontend:
    docker:
      - image: cimg/node:18.16.1
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm --version
            npm install
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  scan-frontend:
    docker:
      - image: cimg/node:18.16.1
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Scan front-end
          command: |
            cd frontend
            npm install
            npm audit --audit-level=critical

  lint-frontend:
    docker:
      - image: cimg/node:18.16.1
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Test front-end
          command: |
            cd frontend
            npm install
            npm run lint

  setup-backend:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]      
      - run: 
          name: Create updated application.properties file
          command: |
            echo "Updating application.properties file in backend/application.properties"
            cd backend
            echo amazon.dynamodb.endpoint=$amazon_dynamodb_endpoint > application.properties
            echo amazon.aws.accesskey=$amazon_aws_accesskey >> application.properties
            echo amazon.aws.secretkey=$amazon_aws_secretkey >> application.properties
            cat application.properties
      - save_cache:
          paths: 
            - backend/application.properties
          key: backend-build

  build-backend:
    executor: java17
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - restore_cache:
           keys: [backend-build]      
      - run:
          name: Compile and Test
          command: |
            cd backend
            mkdir docker
            cat application.properties
            mvn clean test install
            ls -l business/docker
      - run:
          name: Build docker image
          command: |
            cd backend
            docker build --tag=udaroute .
      - run:
          name: Upload docker image to ECR
          command: |
            cd backend
            ls -l business/docker
            echo $ecr_password | docker login --username AWS --password-stdin $ecr_home
            ecrpath=$ecr_home/udaroute:latest
            echo "ERC ID and Image: $ecrpath"
            docker tag udaroute:latest $ecrpath
            docker push $ecrpath

  lint-backend:
    executor: java17
    steps:
      - checkout
      - run:
          name: Checkstyle
          command: |
            cd backend
            mvn checkstyle:checkstyle

  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Setup Kubernetes Cluster
          no_output_timeout: 20m
          command: |
            aws cloudformation deploy \
              --template-file aws/cloudformation/eks-cluster.yaml \
              --tags project=udaroute \
              --capabilities CAPABILITY_NAMED_IAM \
              --stack-name udaroute-eks-cluster
      - run:
          name: Setup Kubernetes Nodes
          command: |
            aws cloudformation deploy \
              --template-file aws/cloudformation/eks-nodes.yaml \
              --tags project=udaroute \
              --capabilities CAPABILITY_NAMED_IAM \
              --stack-name udaroute-eks-nodes
      # Destroy environment on failure
      - destroy-environment:
          workflowId: ${CIRCLE_WORKFLOW_ID:0:7}

workflows:
  default:
    jobs:
      - setup-backend
      - build-backend:
          requires: [setup-backend]
      - lint-backend:
          requires: [build-backend]
      - build-frontend
      - lint-frontend:
          requires: [build-frontend]
      - scan-frontend:
          requires: [build-frontend]
      - deploy-infrastructure
