apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2023-09-16T15:41:44Z"
  generation: 2
  labels:
    app: udaroute-deployment
  name: udaroute-deployment
  namespace: default
  resourceVersion: "397001"
  uid: 21101d04-2453-4b52-bc65-674f106c401f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: udaroute-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: udaroute-deployment
    spec:
      containers:
      - image: 073796236635.dkr.ecr.us-east-1.amazonaws.com/udaroute:latest
        imagePullPolicy: Always
        name: udaroute
        ports:
        - containerPort: 8081
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-09-16T17:33:51Z"
    lastUpdateTime: "2023-09-16T17:33:51Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-09-16T15:41:44Z"
    lastUpdateTime: "2023-09-18T15:06:15Z"
    message: ReplicaSet "udaroute-deployment-dd45b956d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
