server:
  port: ${PORT:8081}

logging:
  level:
    root: INFO


# Google Elevation API
google:
  elevation:
    api:
      url: https://maps.googleapis.com/maps/api/elevation/json
      key: AIzaSyCQmpM6NyoV9JCJRO5HTIeIMEfOFOhKaI4

# OAuth2 security
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 777274664926-p4vof4pqqmh193cds6h2b7fmel2ahae3.apps.googleusercontent.com
            clientSecret: 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
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
